parameters = [
    { name = "dev.frontend.catalogue_url", value = "http=//catalogue-dev.devsig90.online=8080/", type = "String" },
    { name = "dev.frontend.user_url", value = "http=//user-dev.devsig90.online=8080/", type = "String" },
    { name = "dev.frontend.cart_url", value = "http=//cart-dev.devsig90.online=8080/", type = "String" },
    { name = "dev.frontend.shipping_url", value = "http=///shipping-dev.devsig90.online=8080/", type = "String" },
    { name = "dev.frontend.payment_url", value = "http=///payment-dev.devsig90.online=8080/", type = "String" },
    { name = "dev.user.mongo", value = "true", type = "String" },
    { name = "dev.user.redis_host", value = "redis-dev.devsig90.online", type = "String" },
    { name = "dev.user.mongo_url", value = "mongodb=//mongodb-dev.devsig90.online=27017/catalogue", type = "String" },
    { name = "dev.shipping.cart_endpoint", value = "cart-dev.devsig90.online", type = "String" },
    { name = "dev.shipping.DB_host", value = "mysql-dev.devsig90.online", type = "String" },
    { name = "dev.payment.cart_host", value = "cart-dev.devsig90.online", type = "String" },
    { name = "dev.payment.cart_port", value = "8080", type = "String" },
    { name = "dev.payment.user_host", value = "user-dev.devsig90.online", type = "String" },
    { name = "dev.payment.user_port", value = "8080", type = "String" },
    { name = "dev.payment.ampq_host", value = "rabbitmq-dev.devsig90.online", type = "String" },
    { name = "dev.catalogue.mongo", value = "true", type = "String" },
    { name = "dev.catalogue.mongo_url", value = "mongodb=//mongodb-dev.devsig90.online=27017/users", type = "String" },
    { name = "dev.cart.redis_host", value = "redis-dev.devsig90.online", type = "String" },
    { name = "dev.cart.catalogue_host", value = "catalogue-dev.devsig90.online", type = "String" },
    { name = "dev.cart.catalogue_port", value = "8080", type = "String" }
 ]
